federation_version: 2
subgraphs:
  serviceAppointments:
    routing_url: http://localhost:4100/graphql
    schema:
      subgraph_url: http://localhost:4100/graphql
  patients:
    routing_url: http://localhost:4000
    schema:
      subgraph_url: http://localhost:4000
  cases:
    routing_url: http://localhost:4200/graphql
    schema:
      subgraph_url: http://localhost:4200/graphql
  
  